language: php

php:
- "7.0"
- "7.1"
- "hhvm"

matrix:
  fast_finish: true
  allow_failures:
  - php: "hhvm"

services:
- memcached
- redis
- postgresql
- mysql

install:
- composer require "satooshi/php-coveralls" "^1" --no-update --dev
- composer install
- ./travis/install

before_script:
- phpenv rehash
- ./travis/before_script
- cp -v config/framework.dev.yml config/framework.yml
- cp -v config/database.dev.yml config/database.yml

script:
- ./travis/bootstrap
- time php bootstrap.php
- wc -l bootstrap.php
- php bin/phifty asset --link
- phpunit -c phpunit.xml.dist

after_success:
- php vendor/bin/coveralls -v

cache:
  apt: true
  directories:
  - vendor

notifications:
  email:
    on_success: change # default: always
    on_failure: change # default: always
  slack:
    secure: G/7MNT2ZQirPcxX4ui1qn7mfDi29FPIY1ThN4c+KMp5IMLoFtHmrs+3hdCXLQC4mYkWrqLQVQpqRZb92qemZAbRpyaV+1g6IDFzunia95aF2eDRD73TQCNDrKkxhBi69FGo3ToOiB1wTtX/WYLFfkfOmFI43Wu+5fTmvH2mOtIk=
