---
cli:
  bootstrap: "bootstrap.php"
schema:
  auto_id: true
  loaders:
  - Phifty::Schema::Loader::AppSchemaLoader
  - { name: ComposerSchemaLoader, args: ["composer.json"] }
seeds:
databases:
  master:
    driver: mysql
    host: localhost
    database: phifty
    user: root
    pass:
